### ISSUE TITLE
Fix your bugs

### ISSUE THREAD

**Issue by kouge0510** [yash1994/Student-Information-Management-System#2]
[面向对象程序设计课程设计.zip](https://github.com/yash1994/Student-Information-Management-System/files/13597371/default.zip)

I have fixed your bugs and translate it into Chinese.I hope you can first check your program then update it.Your program has many Array out of bounds that cause the program can't work properly and I have fixed it.

**Comment by yash1994** [comment]
Hey, I no longer maintain this project, it was a course project during my undergrads. But, thanks for the update though.
